<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>6/1/0</td>
</tr><tr>
<td>Started on:</td><td>Tue Dec 31 14:23:16 IST 2019</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (36 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.testng.poc.TestCase1.tearDown()'><b>tearDown</b><br>Test class: com.testng.poc.TestCase1</td>
<td><div><pre>java.lang.AssertionError: expected [2] but found [1]
	at com.testng.poc.TestCase1.tearDown(TestCase1.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace34828593", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace34828593'><pre>java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.testng.poc.TestCase1.tearDown(TestCase1.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre></div></td>
<td>0</td>
<td>com.testng.poc.TestCase1@6cc4c815</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.testng.poc.TestCase2.addCustomer()'><b>addCustomer</b><br>Test class: com.testng.poc.TestCase2</td>
<td></td>
<td>0</td>
<td>com.testng.poc.TestCase2@643b1d11</td></tr>
<tr>
<td title='com.testng.poc.TestCase1.login()'><b>login</b><br>Test class: com.testng.poc.TestCase1</td>
<td></td>
<td>0</td>
<td>com.testng.poc.TestCase1@6cc4c815</td></tr>
<tr>
<td title='com.testng.poc.TestCase2.searchCustomer()'><b>searchCustomer</b><br>Test class: com.testng.poc.TestCase2</td>
<td></td>
<td>0</td>
<td>com.testng.poc.TestCase2@643b1d11</td></tr>
<tr>
<td title='com.testng.poc.TestCase1.setUp()'><b>setUp</b><br>Test class: com.testng.poc.TestCase1</td>
<td></td>
<td>0</td>
<td>com.testng.poc.TestCase1@6cc4c815</td></tr>
<tr>
<td title='com.testng.poc.TestCase2.setUp()'><b>setUp</b><br>Test class: com.testng.poc.TestCase2</td>
<td></td>
<td>0</td>
<td>com.testng.poc.TestCase2@643b1d11</td></tr>
<tr>
<td title='com.testng.poc.TestCase2.tearDown()'><b>tearDown</b><br>Test class: com.testng.poc.TestCase2</td>
<td></td>
<td>0</td>
<td>com.testng.poc.TestCase2@643b1d11</td></tr>
</table><p>
</body>
</html>